### ISSUE TITLE
this is not working in firefox

### ISSUE THREAD

**Issue by BhuvneshGupta** [devmark/angular-slick-carousel#107]
Hi, first I was using [this](https://github.com/vasyabigi/angular-slick) slick for angular working fine on both firefox and on chrome. now I am using this current one but it is not working on firefox.

Please tell me how to make it work on all the browsers.

**Comment by douglasdeodato** [comment]
Hi @BhuvneshGupta  what version of firefox you got the problem, can you be more specific about it? thanks

**Comment by BhuvneshGupta** [comment]
it was not working because I was not using ng-if we need to use ng-if="loaded". because data is coming via service and it takes time.

sorry.
so problem is resolved but can you please tell me whats the  difference between these 2 slick 

https://github.com/vasyabigi/angular-slick

https://github.com/devmark/angular-slick-carousel

**Comment by douglasdeodato** [comment]
Hi @BhuvneshGupta  they kinda do the same thing, but the other one looks abandoned last updated 25th of march 2015. :)

**Comment by BhuvneshGupta** [comment]
yeah absolutely @douglasdeodato  that is abandoned and using this my main issue is automatically solved of adaptiveHeight: true . Thanks man:)

Now I am facing one more issue I hope you can help me in that.

Issue is I am having two carousels on same page. And I am using same settings for both the sliders, i.e slideToShow:3

now as my data is dynamic so one slider has 3 images and the other slider has only one image and what wrong is happening is. Slider with 3 images working perfect but slider with one image is not looking good because that single image is stretching and taking width of 3 slides i.e 760px;

How to stop using width?

and yes one more question is that I am using infinite:true so it should slide no matter how many images I have but its not sliding as number of slides = slideToShow.

Thanks :)

**Comment by douglasdeodato** [comment]
@BhuvneshGupta  sorry but do you have a https://jsfiddle.net/ ? sample? I could not understand well what you want. thanks
