### ISSUE TITLE
on responsive resize ng-click stops working

### ISSUE THREAD

**Issue by josthkko** [devmark/angular-slick-carousel#11]
Hi, I have created a plunkr showing the problem:
[Plnkr](http://plnkr.co/edit/boZ7786DGZMdBdLdtoij?p=preview)

Basically I create a list of items with ng-repeat and each of them should execute a function on click. This happens, but only if the starting resolution is bigger than 1024, so the list does not get paginated. If the page is resized to lower than that, items are correctly paginated, but ng-click event stops working.
Also if the page starts in a lower resolution, the ng-click events are not firing.

I think this is a bug, unless you have any other ideas? Would really appreciate some help with this.

Thank you.

**Comment by josthkko** [comment]
@kbdaitch Also the last button does not seem to scroll to the end of the list.

**Comment by kbdaitch** [comment]
@josthkko You bring up some good issues. I tested your plunkr, seems like a bug but I am not sure where. There are couple moving parts here: the slick plugin that this directive uses, and then angular ngClick directive itself. I would recommend testing your usecase with just the other [angular-slick](https://github.com/vasyabigi/angular-slick) plugin out there.

Now, looking at my own use of this directive, I am seeing that I never used it in production with `ngClick`. I use `ui-router` and I have `ui-sref` on the slickified elements - my app also doesn't use varying resolutions - we are fixed at 1080p.

**Comment by josthkko** [comment]
@kbdaitch Tried it with the other plugin and it works. Thank you.

**Comment by Hirbod** [comment]
Now I do have the same problem. I have a ng-click event and want to open a lightbox. It fails. But when I look at the DOM, I see ng-click is triggerin, but it seems like it's some kind of isolated scope and my function does not fire..

**Comment by Hirbod** [comment]
I guess you should use $templateCache to provide scope-access..

**Comment by kbdaitch** [comment]
@Hirbod yeah, perhaps I should have never removed the transclude functionality. Part of the revision when I removed it, was to experiment with my use case. It probably limited the use of the directive at that point.

Did you give the other more famous directive linked [above ](https://github.com/kbdaitch/angular-slick-carousel/issues/11#issuecomment-75405470) a try?

**Comment by Hirbod** [comment]
Yes I did, and it's very buggy. That's why I changed to yours. I just need to have access to the scope, then I'm totally fine with your plugin

**Comment by kbdaitch** [comment]
How about you fork the directive, and add your fields [here](https://github.com/kbdaitch/angular-slick-carousel/blob/master/src/slick.coffee#L69-L76), and release it in your own name on bower.

Alternatively, you could remove the `src` attribute, add `transclude: true` to your directive definition, and you should have scope access from the controller. The usage of your new directive would then look like:

```html
<slick ...>
 <!-- Contents of your src template -->
</slick>
```

And your templateUrl/tempalate for the directive could be as simple as:
```html
<ng-transclude></ng-transclude>
```

**Comment by Hirbod** [comment]
The fields are totally the same? Only big difference I see here is the missing transclude: true

**Comment by Hirbod** [comment]
Is there any reason why you should not wan't to have access to the scope and limited your plugin this way?

**Comment by kbdaitch** [comment]
Just added the gitter badge to readme. Lets take it over there?

**Comment by Hirbod** [comment]
ok

**Comment by kbdaitch** [comment]
For context, I limited the plugin this way consciously.

I wanted to provide the definition for on-finish-render and wanted to enforce it in transcluded content which wasn’t possible so I decided to take away the user’s flexibility, moving to 2.x.

**Comment by kbdaitch** [comment]
@Hirbod thoughts?

**Comment by babajem** [comment]
I have the same problem with ng-click not working in responsive, have you find a solution? Thanks.

**Comment by JacksonChristopherHowell** [comment]
same problem

**Comment by mihaituhari** [comment]
Still same problem after so long :(
