### ISSUE TITLE
src doesnt support dynamic $scope-bound attributes

### ISSUE THREAD

**Issue by smcelhinney** [devmark/angular-slick-carousel#12]
This works 

```
<slick src="some-template.html"><slick>
```

This doesnt. 

```
<slick src="{{templateName}}"><slick>
```

Any reason why?

**Comment by kbdaitch** [comment]
@smcelhinney Look at this SO [answer](http://stackoverflow.com/a/14632332). So it can be done, but we would have to rely on the lower-level `$http` and `$compile` apis. What's your use case like? Do you think this to be useful to a large userbase?

**Comment by smcelhinney** [comment]
Not sure its relevant to a wider group, no, but my use case is that I need to display a different template based on certain `$scope` variables (ie: load a single slick directive, and change the card src based on a combination of different $scope attributes).

**Comment by kbdaitch** [comment]
@smcelhinney Actually, found a better [solution](http://stackoverflow.com/a/21835866) using `ng-include`. Would you like to take a knack at it and submit a PR?
