### ISSUE TITLE
Find new owner for this directive GitHub project

### ISSUE THREAD

**Issue by kbdaitch** [devmark/angular-slick-carousel#21]
Once found:

1. Move the repo to their account
2. Move the bower publish over to them

cc: @sbeam @rigobcastro @devmark 

As announced on the project page readme on top.

**Comment by kbdaitch** [comment]
@devmark I have decided to hand it over to you.

I have initiated the transfer, you may have to delete the fork you have with the same name before you accept the transfer.

I also have unpublished the bower package, so you can republish with the same name `angular-slick-carousel` from your GitHub repo. Lets figure this out soon before others suffer from a broken build.

**Comment by kbdaitch** [comment]
Should be as easy as running `bower register angular-slick-carousel https://github.com/devmark/angular-slick-carousel` once you have accepted the GitHub repo transfer.

**Comment by kbdaitch** [comment]
In the meanwhile, if `bower install` is broken for any of you, please follow [this](http://stackoverflow.com/questions/20196707/can-i-add-a-git-repository-to-my-bower-json) SO post to depend on the repo directly.

I hope the flux will the minimal and that there would be a responsible maintainer going forward :)

**Comment by devmark** [comment]
bower package exists. have unpublished already?

**Comment by kbdaitch** [comment]
I thought I unpublished it. Let me check it tomorrow.

**Comment by kbdaitch** [comment]
I got  a chance to check it. Turns out you have to make curl call like so, mentioned [here](http://stackoverflow.com/questions/27858666/moving-the-github-repo-thats-a-bower-package):

```sh
curl -X DELETE "https://bower.herokuapp.com/packages/PACKAGE?access_token=TOKEN"
```

in addition to calling `bower unregister` which I had done.

**Comment by kbdaitch** [comment]
Complete.
