### ISSUE TITLE
Updating a view inside an existing slide

### ISSUE THREAD

**Issue by yougotashovel** [devmark/angular-slick-carousel#24]
Hi, here's my issue:

1. My slider consists of 4 slides.
2. Each of these slides has a unique *'ui-view'* that loads content.
3. This works fine initially, but when i try to update one of the views:
4. It doesn't do anything to the existing slide.
5. It adds another version of the updated slide outside of the slide-track.

In the Elements tab in Chrome tools i can see the *'slick-cloned'* slides in *'slide-track'*. However it looks like the angular inserted markup e.g. `<!-- uiView:slide1 -->` remains outside *'slide-track'*.  

Can anyone suggest how to resolve this issue? Below is how the code looks at different stages:

Original HTML:
```
<slick settings="slickPanels">
	<div ui-view="slide1"></div>
	<div ui-view="slide2"></div>
	<div ui-view="slide3"></div>
	<div ui-view="slide4"></div>
</slick>
```
Before view update:
```
<slick settings="slickPanels">
	<!-- uiView: slide1 -->
	<!-- uiView: slide2 -->
	<!-- uiView: slide3 -->
	<!-- uiView: slide4 -->
	<div aria-live="polite" class="slick-list draggable">
		<div class="slick-track" style="opacity: 1; width: 45000px; transform: translate3d(-1000px, 0px, 0px);" role="listbox">
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide1" class="ng-scope" style=""></div>
			</div>
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide2" class="ng-scope" style=""></div>
			</div>
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide3" class="ng-scope" style=""></div>
			</div>
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide4" class="ng-scope" style=""></div>
			</div>
		</div>
	</div>
</slick>
```
After update:
```
<slick settings="slickPanels">
	<!-- uiView: slide1 -->
	<div ui-view="slide1" class="ng-scope"></div>
	<!-- uiView: slide2 -->
	<!-- uiView: slide3 -->
	<!-- uiView: slide4 -->
	<div aria-live="polite" class="slick-list draggable">
		<div class="slick-track" style="opacity: 1; width: 45000px; transform: translate3d(-1000px, 0px, 0px);" role="listbox">
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide1" class="ng-scope" style=""></div>
			</div>
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide2" class="ng-scope" style=""></div>
			</div>
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide3" class="ng-scope" style=""></div>
			</div>
			<div class="slick-slide slick-cloned" role="option" aria-hidden="false">
				<div ui-view="slide4" class="ng-scope" style=""></div>
			</div>
		</div>
	</div>
</slick>
```

**Comment by devmark** [comment]
could you make a PR? thanks

**Comment by yougotashovel** [comment]
While i was creating a plunkr i found a workaround, but here is the issue so you can see the problem:
http://plnkr.co/edit/RZ5ImTSd7dWZBPkvFpiI?p=preview

Here's my current workaround:
I added a child `<div>` inside each slide, and moved the `ui-view` to the new div.
http://plnkr.co/edit/bV7cZuBDzQdfcRv1I7tP?p=preview

**Comment by yougotashovel** [comment]
I found another issue with the `ui-view` regarding infinite carousel.

Slick essentially duplicates the slides and adds them to the `slick-track` to give the impression of infinite?  Well the duplicate slides don't contain the `ui-view`.

I'm guessing either:
1. the duplicate/copy/clone method doesn't account for `ui-view`
2. or angular messes up when it sees two versions of the same `ui-view`

Is there a possible workaround for this?

**Comment by devmark** [comment]
sorry for delay reply.
http://plnkr.co/edit/cQj6Qjw5Mc43NTpK3MDM?p=preview

all you have to updated `data` attribute. so that slick can refresh slides.

**Comment by yougotashovel** [comment]
I simplified my example for this issue.  This solution isn't really for my case and seems to change all the data at once regardless which button is clicked.

I'm using the route to update the template inside each view separately, and each slide will have different content and layout.

**Comment by FDiskas** [comment]
Probably the same issue http://jsbin.com/maqokememe/1/edit?html,js,output
