### ISSUE TITLE
r.slick is not a function

### ISSUE THREAD

**Issue by smlombardi** [devmark/angular-slick-carousel#26]
TypeError: r.slick is not a function

Just added the div to my file and the config to my model...

**Comment by yougotashovel** [comment]
Do you have both the jQuery and Angular versions of Slick linked?

I had this problem when only one of them was.

**Comment by smlombardi** [comment]
you need to load both?

**Comment by yougotashovel** [comment]
Yes.

It took me a while to figure out you needed both, as it's not clearly stated in the readme, and the file names all look so similar in the example code.

I'm fairly new to Angular, so i don't know if this kind of plugin is usual.  I was expecting a port from jQuery to Angular.  But 'angular-slick-carousel' is essentially an extender for the jQuery Slick plugin.  Not a replacement for it.

**Comment by smlombardi** [comment]
Thanks.  I have seen both types of these plugins.  But it's very annoying its not in the readme.

**Comment by devmark** [comment]
updated README.
