### ISSUE TITLE
duplicate event handlers registered after changing bound data

### ISSUE THREAD

**Issue by avivr** [devmark/angular-slick-carousel#30]
If you pass event handlers in slick options, e.g.
```
event: {
          beforeChange: function() {
            console.log("before change called");
            },
          afterChange: function() {
            console.log("after called");
            }
      }
```

and you change/replace the bounded data.

the event handler get registered each time the data is changed, and the previous doesn't get unregister.
which cause it to be called multiple time (as many times as you've changed data).

you can see a sample here:
http://plnkr.co/edit/qOQ1cOHVPwvxCF933lbm

click the 'update view' button multiple times to add more items to the bounded data list.
and watch the console log window while you move slides with the next/prev arrows.

**Comment by devmark** [comment]
it should be work on ver 3.0.5, slick with ngIF
 take a look https://github.com/devmark/angular-slick-carousel#slidedata

**Comment by devmark** [comment]
take a look ver 3.0.6
thanks !

**Comment by avivr** [comment]
i can't get it to work, even with the new version and using the ng-if as in the example.
can you please modify the plnkr above to demo the fix?
thanks!

**Comment by devmark** [comment]
http://plnkr.co/edit/GLAFTryRy3jYLZ793tWf?p=preview
