### ISSUE TITLE
SliceGoTo is not working in controller

### ISSUE THREAD

**Issue by sachinlogiciel** [devmark/angular-slick-carousel#31]
$timeout(function(){
    $scope.slickConfig.method.slickGoTo($scope.index);
});

$scope.slickConfig.method.slickGoTo is not a function

**Comment by devmark** [comment]
Could you make a demo ?
You could fork this http://plnkr.co/edit/mKGLct?p=info

**Comment by sachinlogiciel** [comment]
check this 
http://plnkr.co/edit/hQWpQc4GFQKcV8BPtPLf?p=preview

**Comment by devmark** [comment]
if u really need to use `slickGoTo` after slick inited. 
maybe u should use 

~~~~
    $scope.slickConfig = {
      autoPlay:false,
      method: {},
      event: {
        init: function(event, slick) {
          slick.slickGoTo(2);
        }
      }
    };

~~~~

OR timeout 1000 or other
~~~~
            $timeout(function () {
                $scope.slickConfig.method.slickGoTo(4);
            }, 1000);
~~~~

**Comment by sachinlogiciel** [comment]
OK Thanks Its working now using init event. :smiley: Cheers :beers:
