### ISSUE TITLE
need to disable right end navigation of the carousel when I have second image at the left end

### ISSUE THREAD

**Issue by madasuk** [devmark/angular-slick-carousel#32]
Hi, I have total 5 images and I am showing 4 images at a time in my carousel with 1 image slide at a time. Now at the left end when I have 2nd image (i.e, on the right end I have 5th image) at the time the right navigation controller of the carousel has to be disabled and there should not be any more sliding. How can I achieve this with this slick carousel?

**Comment by devmark** [comment]
Sorry for delay 

you mean when slide to end , should not still can slide to 1st slide?
You could use `infinite: false`
```
$scope.slickConfig = {
    autoplay: true,
    infinite: false,
    speed: 300,
    slidesToShow: 4,
    slidesToScroll: 1,
    event: {
        beforeChange: function (event, slick, currentSlide, nextSlide) {
        },
        afterChange: function (event, slick, currentSlide, nextSlide) {
        }
    }
};
```

If i get wrong what you mean, maybe you can use `afterChange` event to do it
If need more help you can fork this http://plnkr.co/edit/BszBjj?p=preview and show to me

**Comment by madasuk** [comment]
Thanks devmark for the reply, this is what I want. Sorry for the delay due to weekend travel.
