### ISSUE TITLE
npm and package.json

### ISSUE THREAD

**Issue by monteirocode** [devmark/angular-slick-carousel#35]
Hi, coud you please add a main file direction and publish the latest version to npm which you'll need to update the package.json version number.

package.json
```json
{
  "name": "angularSlickCarousel",
  "version": "3.0.9",
  "main": "dist/angular-ui-router.js"
}
```
```sh
$ npm publish
```
Adding a  `main` allows users to use it as a npm module in Browserify/Webpack
```js
var angularSlickCarousel = require('angular-slick-carousel');
// or with in ES6
import angularSlickCarousel from 'angular-slick-carousel';
```
Otherwise it throws this error
```sh
ERROR in ./app/scripts/app.js
Module not found: Error: Cannot resolve module 'angular-slick-carousel'
```

**Comment by devmark** [comment]
Updated 

But it seems someone has published this package. 
So i can't publish it now. But i have sent a email to him that tel him it is available to publish new version.
