### ISSUE TITLE
initialSlide option only working briefly before defaulting to first slide

### ISSUE THREAD

**Issue by OneHP** [devmark/angular-slick-carousel#37]
Using the latest versions (slick: 1.5.8, angular-slick-carousel: 3.0.9) setting the initialSlide in options works only momentarily before the carousel changes back to the first slide.

http://plnkr.co/edit/fYIvLiX6Q6d0ZdWQYKzW?p=preview

A working example can be made using an old version of slick: 1.3.15

http://plnkr.co/edit/kENaWAIVGETbBCV8JAfo?p=preview

**Comment by devmark** [comment]
Hello @OneHP 
Please try 3.1.0 version. tell me if get problem.

**Comment by OneHP** [comment]
Hi @devmark 

It seems to work on my plunkr. I can't check it with my actual application as 3.1.0 isn't in npm yet (https://www.npmjs.com/package/angular-slick-carousel).

Thanks for getting this fixed so quickly.

**Comment by devmark** [comment]
npm updated :+1:

**Comment by OneHP** [comment]
Works great. Thanks again.
