### ISSUE TITLE
filter with ng-repeat

### ISSUE THREAD

**Issue by bwasnie1** [devmark/angular-slick-carousel#38]
Hello,

I'm facing the issue, that I cannot rerender slick when I bind a filter input to my ng-repeat (I use html cards).

As soon as the filter triggers, all items disappear.

**Comment by devmark** [comment]
please make a demo plnkr.co 
you could fork http://plnkr.co/edit/BszBjj

**Comment by umdstu** [comment]
@devmark I came across this as I had the same issue. It took me a while to reproduce in your (working) example, but finally got it. It seems that by adding {rows: 2} to the config it breaks the filtering in your example and my own code.  Here's a fork of your example that shows this behavior:

http://plnkr.co/edit/NN63HQmCPlVakcj9Jps8?p=preview

Thanks

**Comment by devmark** [comment]
Hello. 

http://plnkr.co/edit/HtqKINMPHxCwQqMfUzFZ?p=preview

1. use ng-change to restart slick.
2. use $watch to do it.

**Comment by umdstu** [comment]
@devmark Thanks, that worked great. Now that it works, it seems filtering has an odd effect on the organization of the results. You can see it here in action:
http://plnkr.co/edit/qUIdg33h6cdFKGiMeiMA?p=preview

I feel like this is again a byproduct of the `rows` option.

You can see the behavior in the demo if you type `1` in the input. Four results are present, as expected.

Odd behavior: Slick configuration is for 2 rows, 3 at a time. I expected the four elements present to be 3 on the first row, and 1 on the second row. However, there are 2 on each row. Is this intended? I'm trying to get a demo of the original slick.js working to see if I can reproduce the behavior outside of angular filtering.

**Comment by Samadvpd** [comment]
@devmark thank you very much sir... 💯

**Comment by reissr** [comment]
Perfect!
TD;DR - Use ng-if="viewLoaded", and change the viewLoaded to false and then back to true after loading the content.
Inspired by the provided plnkr above - http://plnkr.co/edit/BszBjj?p=preview
