### ISSUE TITLE
customPaging is not a function

### ISSUE THREAD

**Issue by ghoshkaj** [devmark/angular-slick-carousel#44]
When trying to use customPaging, I'm running into this error: customPaging is not defined. I can't find any code examples for it, and just passing it in as a directive isn't working. The console shows that error and nothing is rendered to DOM.

This is my code -- for reference: 
```
<slick dots=true custom-paging="customPaging(slick, index)">
  <div verticalBar title="Population"></div>
  <div horizontalBar title="Age Gender"></div>
</slick>
```

and this customPaging function in my controller:
```
 $scope.customPaging = function(slick, index){
      return '<button class="tab">' + $(slick.$slides[index]).attr('title') + '</button>';
 };
```

**Comment by devmark** [comment]
Sorry for delay. 
take a look 3.1.2 version.

**Comment by ghoshkaj** [comment]
Thanks
