### ISSUE TITLE
The sync carousel broken with dynamic data.

### ISSUE THREAD

**Issue by nguyenthong** [devmark/angular-slick-carousel#47]
When I use directive in sync carousel setting when the data is updating the order tag in the carousel messing up. Or with the multiple slidesToShow setting when the data updating by Angular, all the elements not stay inside carousel but instead it move outside and display vertically.

**Comment by devmark** [comment]
Sorry for delay, could you make a plunkr to me?
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by nguyenthong** [comment]
Here is the plunker http://plnkr.co/edit/9CT24i?p=preview.

**Comment by devmark** [comment]
You mean when click `update view` will break first slick ?

**Comment by nguyenthong** [comment]
yes

**Comment by devmark** [comment]
first slick should also add `ng-if="viewLoaded"` if you using same data

**Comment by nguyenthong** [comment]
oh, my mistake!. Thank you so much for answering me!

**Comment by devmark** [comment]
Cheer :+1:
