### ISSUE TITLE
how to set current slide index?

### ISSUE THREAD

**Issue by rickray21** [devmark/angular-slick-carousel#49]
I am using angular slick and it is working fine. But I have to set the current slide position on run time depending on the api data. There will be some conditions. Sometime it will start from number 2 slide, sometime it can be 4 or sometime it can be from last. Depending upon the position of the data I have to set the current slider position. 

How do I set it? The slickgoto is not working in that case. Please help.

**Comment by devmark** [comment]
use Method function:
```
slickConfig.method.slickGoTo(2)
```

use Slick callback:
```
 slick.slickGoTo($scope.currentIndex);
```

if other cases, maybe you need to make a plunkr to me.
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by rickray21** [comment]
Yap, slickGoTo is working right now. I have use it onInit with $timeout and it is working. Previously it was not rendering that is why I have to use $timeout. Now it is working perfectly.
