### ISSUE TITLE
Error sliding from first to last and last to first

### ISSUE THREAD

**Issue by rafa-as** [devmark/angular-slick-carousel#51]
Hi @devmark

If you check your example (index.html) and go from the first slide to the last slide you can see how to the last slide not appears correctly.

One trick is execute unFilter after initialize the slick, but is not very elegant...

I checked the jquery version, slick version and a lot of options but i don't have the correct solution.

Thanks!

**Comment by devmark** [comment]
I have tried some cases : 
1. click arrow to last slide and first slide
2. click filter ,then do click arrow to last slide
3. click dots to last slide and go to first slide

nothing error i get.

Could you  make a plunkr to me. Thanks
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by rafa-aguilar** [comment]
Sorry @devmark but i can't open plunkr, you can provide another?

**Comment by devmark** [comment]
it seems plunkr server down.

maybe have a look jsbin, this is create by other ppl. 
http://jsbin.com/vufeda/edit?html,js,output

**Comment by rafa-aguilar** [comment]
You can see the error in your own code in this screencast of your demo example: https://www.dropbox.com/s/rte1569yb7z167t/angular-slick.mov?dl=0

**Comment by devmark** [comment]
get your problem. 
what browser , angular-slick-carousel you using?

**Comment by rafa-aguilar** [comment]
Safari, Chrome, Firefox and IE under Mac and Windows. 

Sorry for my poor english.

**Comment by rana3012** [comment]
Hey first of all thank you for this directive but I also have come across this same issue. Its when the `infinite` is set to true. Can you please try with it on ?

**Comment by rana3012** [comment]
+1 Having the same issue. Navigate through all slides then click next which takes back to the first slide and there comes the issue. You can find the issue even after going back and forth the slides.

**Comment by devmark** [comment]
will take a look soon.
Thanks for report

**Comment by rana3012** [comment]
I don't know if its the same issue but I see a strange jerk when the the `centerMode` is set to `true`. Initially the width of my `slick-slide` is `201` but after switching to next slide it turns `221` and a slide just comes down which is undesirable.  

By the way, thank you for the directive and staying alert to issue reports.

**Comment by devmark** [comment]
@rana3012 could you make a demo?

**Comment by rana3012** [comment]
Hi.. Sorry for the delay.. I couldn't get a working fiddle but i'm sharing my use case. Please check [this fiddle](https://jsfiddle.net/rana3012/wfphwL9e/3/).

**Comment by rana3012** [comment]
https://github.com/kenwheeler/slick/issues/234
