### ISSUE TITLE
slickness.slick is not a function

### ISSUE THREAD

**Issue by JaKXz** [devmark/angular-slick-carousel#52]
Hi, I'm getting this error:

```
TypeError: slickness.slick is not a function
    at angular-slick.js:167
    at angular.js:17855
    at completeOutstandingRequest (angular.js:5507)
    at angular.js:5784
```

when trying to repeat over a list of given items, as shown in my following gist

Here's my directive definition and template: https://gist.github.com/JaKXz/367921c102b838221565

Any ideas? I'm poking around the source myself but I'm not sure where to start. Thanks in advance, @devmark !

**Comment by devmark** [comment]
Happy Christmas!

You should load `slick` plugin before `angular-slick-carousel`
```
    <script src="../bower_components/slick-carousel/slick/slick.js"></script>
    <script src="../bower_components/angular-slick-carousel/dist/angular-slick.min.js"></script>
```

also you have to load slick's css as well

**Comment by JaKXz** [comment]
@devmark Happy Christmas to you too :)

I have `slick-carousel/slick/slick.min.js` loading before `angular-slick.js` (since you have `slick` listed as a dependency for `angular-slick`).

**Comment by devmark** [comment]
If you confirm you loaded `slick` before `angular-slick-carousel`
then take a look this demo. 
http://plnkr.co/edit/9goFW6?p=preview

If still can't find that problem, then you can make a plunkr to me. 
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by bhosalemahesh899** [comment]
Hi jaKXz,
you need to jquery carousel  slick plugin

**Comment by Jeroen-Hulsman** [comment]
I ran into the same issue - turned out `jquery `also needs to be loaded before `angular`. That fixed this specific error for me.
