### ISSUE TITLE
I have error 

### ISSUE THREAD

**Issue by bhosalemahesh899** [devmark/angular-slick-carousel#54]
TypeError: slickness.slick is not a function
    at angular-slick.js:167
    at angular.js:17918
    at completeOutstandingRequest (angular.js:5552)
    at angular.js:5829

**Comment by devmark** [comment]
If you are sure that you loaded slick before angular-slick-carousel
then take a look this demo. 
http://plnkr.co/edit/9goFW6?p=preview

If still can't find that problem, then you can make a plunkr to me. 
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by bhosalemahesh899** [comment]
yes,
thanks its working now.
