### ISSUE TITLE
Dynamic Settings

### ISSUE THREAD

**Issue by ronildo** [devmark/angular-slick-carousel#55]
I have two carousels in my page, they are inside a ng-repeat.
I need the ability to delete items from it.

Is that possible?

**Comment by devmark** [comment]
take a look : https://github.com/devmark/angular-slick-carousel#slide-data

**Comment by ronildo** [comment]
Let me put my code here so you can understand what I'm talking about:

```
<div ng-repeat="item in items">
  <slick slides-to-show="4" settings="configs">
  </slick>
</div>
````

How can I remove slides from carousel one or carousel two (considering my ng-repeat is iterating two times).

I hope my question my more clear now :)

ps: Thank you so much for you great work here.

**Comment by devmark** [comment]
```
$scope.slicks = [{name: 'slick1', enabled: true}, {name: 'slick2', enabled: true}, {name: 'slick3', enabled: true}];
```

```
 <div ng-repeat="slick in slicks">
    <slick data="number" settings="slickConfig" ng-if="slick.enabled">
        <div ng-repeat="i in number">
            <div class="row" ng-include="'tpl.html'"></div>
        </div>
    </slick>
    <button ng-click="slick.enabled=!slick.enabled" class="btn">toggle enabled </button>
</div>
```


this work for you?

**Comment by aszmyd** [comment]
Hi Guys, to simplify explaining such errors i think we should preparing some code examples. I've created starting template for `angular-slick-carousel` script here: http://codepen.io/aszmyd/pen/LGdoyV
Feel free to fork it and prepare some examples of use cases.

**Comment by GrofGraf** [comment]
Hello again mr. Devmark. Thank you for your help so far. I came to another issue I cant't resolve. I have slick with dynamic data in infinite mode. I would like the numbers to increment or decrement, regarding the direction slick is moving. Although my data changes, slick is reseting to default values everytime i hit the edge, is there any way to fix this? 
Here is my plunker: 
[](http://plnkr.co/edit/mzbO1e?p=preview)

**Comment by devmark** [comment]
open it if need any help

**Comment by sumeetmobiwebtech** [comment]
I have two carousels in my page, they are inside a ng-repeat.
But when a slide first slider then second slider is also sliding automatically.
i do not need that second slider automatically slide.
Can anyone tell me how to resolve ?

**Comment by GrofGraf** [comment]
@sumeetmobiwebtech 
I created a new Plunker fork with two carousels for you. Hope it can serve you as a starting point. If you  want more help, better elaborate your problem (demo example would be a nice start).

http://plnkr.co/edit/x1fVH1NSrOL2EyvGozYz?p=preview

**Comment by sumeetmobiwebtech** [comment]
@GrofGraf 

When it come from dynamic,this is i am using


<div class="features_product  sec_pad cyan_bg" ng-repeat="laptop in laptopfrontresults">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        
                        <div class="product_box_row">
                            <div class="row">
                                <div class="see_more" ng-if="(laptop.productData).length>4">
                                    <a ng-click="headingsPage(laptop.id)" class="btn btn_see_more">See More</a>
                                </div>
                               
                                <slick class="slider" settings="slickConfig" ng-if="(laptop.productData).length" prev-arrow=".left" next-arrow=".right">
                                    <div class="col-sm-3" ng-repeat="product in laptop.productData">
                                        <div class="product_box">
                                            <div class="hover_box">
                                                <a ng-click="showProduct(product.id,laptop.type)">View More</a>
                                            </div>
                                            <div class="product_top">
                                                <div class="product_img">
                                                    <a ng-click="showProduct(product.id,laptop.type)">
                                                      <img src="{{product.image_url}}" class="img-responsive" alt=""/>
                                                    </a>
                                                </div>
                                                <div class="product_name_box">
                                                    <a ng-click="showProduct(product.id,laptop.type)">
                                                        <div class="pro_name">{{product.product_name}} </div>
                                                    </a>
                                                    <div class="pro_price">₹ {{product.product_price_flipkart}} INR</div>
                                                    
                                                   
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </slick>
                                <a href="" class="left">
                                  <span class="icon-arrow-left"></span>
                                </a>
                                <a href="" class="right">
                                  <span class="icon-arrow-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

**Comment by GrofGraf** [comment]
At first glance it looks like this is happening because you reference a class for sliding prev-arrow=".left" next-arrow=".right", that is contained on every link. Maybe change a class reference to dynamic ID.

@sumeetmobiwebtech
please make a demo.
You could fork these:

http://codepen.io/aszmyd/pen/LGdoyV
http://plnkr.co/edit/9goFW6?p=preview

**Comment by sumeetmobiwebtech** [comment]
@GrofGraf 

Thanks you so much

You save my lot of time
Thanks again
