### ISSUE TITLE
How to wait for the images to load and then start the carousel?

### ISSUE THREAD

**Issue by mmswi** [devmark/angular-slick-carousel#57]
Hello,

I'm having these issues: the slick carousel doesn't seem to load if the images take longer to load.

How can I initialize the slick carousel after the content is loaded?

If you look on my website, you will see that the images are one under the other. Here is the live exampe: http://mmswi.com/gademm/index.html#/product/51Petit

On my localhost the carousel works fine, but only after I cache it. At the first page load, the images appear one under the other.

In this other plugin (https://github.com/vasyabigi/angular-slick), I see the carousel has something like <slick init-onload=true data="awesomeThings">. Does your plugin have something similar?

Thanks for the help,
Mihai

**Comment by mmswi** [comment]
Update: decided to use the other carousel (https://github.com/vasyabigi/angular-slick), until I get an answer here, so I can show the customer the website progress.

**Comment by devmark** [comment]
Hello. Sorry for delay.

please make sure inject `angular-slick` plugin in `head` html section
then you can try something like: 


`slick` plugin data-lazy function
---------------------
have a demo:
http://plnkr.co/edit/sL71LFvGunFlKYZAFqUM?p=preview


```
<img src="http://placehold.it/1024x400" data-lazy="http://cdn.urbanislandz.com/wp-content/uploads/2011/10/MMSposter-large.jpg" alt="">       
```

```
$scope.slickPanels = {
      lazyLoad: 'ondemand',
};
```

you can replace `http://placehold.it/1024x400` to `loading gif`

---------------------

**Comment by mmswi** [comment]
Hello devmark,

Thanks for the quick reply! 

I will try this solution today or tommorow and let you know the result!

Thanks
