### ISSUE TITLE
How to update slick when ng-repeat collection object changes 

### ISSUE THREAD

**Issue by sgrandhe** [devmark/angular-slick-carousel#59]
Hi,

I have problem updating slick when loaded new images in to ng-repeat collection object. images are loading one under another.

thanks.

**Comment by devmark** [comment]
take a look
https://github.com/devmark/angular-slick-carousel#slide-data

**Comment by BenevidesLecontes** [comment]
devmark is there another way to update carousel elements without setting carousel to false? Because this way cause carousel blinking when the carousel update.

**Comment by GrofGraf** [comment]
Hello. If you are asking about adding an elemnt to collection, I used slickAdd() function, because that was only way i managed to add item to collection without blinking. I was adding a directive to collection, like so:  
```
var mydir='<my-directory></my-directory>';
var compiled=$compile(mydir)($scope);
$timeout(function(){
      $scope.slickSettings.method.slickAdd(compiled);
})
```

**Comment by BenevidesLecontes** [comment]
@GrofGraf thanks for sharing your solution, I already solved this doing like you did. Here what I did:
var template = document.getElementsByClassName('secondSlide');
    $timeout(function () {
      $scope.slickConfig.method.slickAdd(template);
    }, 2000);
