### ISSUE TITLE
Add custom angular directive or ng-template with slickAdd()

### ISSUE THREAD

**Issue by GrofGraf** [devmark/angular-slick-carousel#60]
Hello.

I was wondering if i can add my own angular directive or ng-template with slickAdd() function, and if possible, how to do it. Any help would be appreciated.

**Comment by devmark** [comment]
Sorry for delay, Will make a demo to you soon.

**Comment by GrofGraf** [comment]
Actually i sort of made it work. Had to bind scope to the directive with ng-bind. But now i have another problem. I have inputs with unique id's. Before, my list was in ng-repeat and i made id's based on $index. Now i am trying to make id's based on currentIndex that is changing in afterChange, but if i change one id, it happens to all the others too. Is it possible to somehow access current slide data? I see that parent element has attribute data-slick-index, and that is what i am trying to access.

**Comment by devmark** [comment]
https://github.com/devmark/angular-slick-carousel#faq

You should create another variable to store id which base on currentIndex.
