### ISSUE TITLE
Previous and next arrow stopped working after upgrading from 3.1.0 to 3.1.4

### ISSUE THREAD

**Issue by hfreire** [devmark/angular-slick-carousel#62]
Hi!

When upgrading from 3.1.0 to 3.1.4 the prevArrow and nextArrow used in the slick directive stopped working as they used. I was passing an id selector on them. Did this directive stop supporting these selectors through these options?

Here is a plunkr to demonstrate this:
http://plnkr.co/edit/jbyD6yHomMM0qeM5fb1N?p=preview

**Comment by devmark** [comment]
Hello Hfreire, 
can this help for you?

http://plnkr.co/edit/N5KlkO22Im7XErtamKGi?p=preview

```
      prevArrow: '#prevvv',
      nextArrow: '#nexttt',
```
