### ISSUE TITLE
not working with firefox. 

### ISSUE THREAD

**Issue by dbelieves** [devmark/angular-slick-carousel#64]
i see vertical stacking in firefox.
works fine in chrome.

any help?

**Comment by devmark** [comment]
Hello. 
will take a look tmr.

**Comment by dbelieves** [comment]
Any fix?

**Comment by capncavemann** [comment]
Any word?

**Comment by capncavemann** [comment]
<img width="1440" alt="screen shot 2016-04-26 at 12 21 01 pm" src="https://cloud.githubusercontent.com/assets/18668401/14825837/745c0f88-0ba9-11e6-819d-4f671cf88071.png">

**Comment by devmark** [comment]
i am work fine in firefox. please make a demo you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by javo01** [comment]
I think the issue is with Firefox and Angular Material, i'll do a plunkr later but here are some caps of the issue in my project.

Cap from Chrome:
![image](https://cloud.githubusercontent.com/assets/4388505/15374041/1123af40-1d0e-11e6-8630-d0f978b52df1.png)

Cap from Firefox:
![image](https://cloud.githubusercontent.com/assets/4388505/15374064/2be01508-1d0e-11e6-9384-7a1aaef87e08.png)

**Comment by capncavemann** [comment]
I too am using angular material, you may be on to something.  A CSS override?

**Comment by javo01** [comment]
I thought that by your log, i don't think that is just a CSS override cause the buttons are not getting added, i'll run some test and get back here

**Comment by javo01** [comment]
@capncavemann did you found something? 

i fond that in slick.js (not in angular-slick-carousel) in the line  506: 

`_.$slides =
            _.$slider
                .children( _.options.slide + ':not(.slick-cloned)')
                .addClass('slick-slide');`

the children are missing, but only in FF and they exist in the parent if you log it.

**Comment by capncavemann** [comment]
@javo01 I have not. I dropped the carousel for the time being. were you able to fix slick.js locally? or did you report it as an issue with that repo?

**Comment by javo01** [comment]
@capncavemann i just made it, it was a problem in my view i used ng-if="vm.arrayOfThings" and in every browser worked except FF, i change it to ng-if="vm.arrayOfThings.lenght" and everything works.

**Comment by capncavemann** [comment]
@javo01 thx, will try it out
