### ISSUE TITLE
CSS transitions not working

### ISSUE THREAD

**Issue by artuska** [devmark/angular-slick-carousel#65]
Angular Slick Carousel uses `left` style when moving the `.slick-track` block instead of using `transform: translate3d(0px, 0px, 0px);` CSS transitions. The animation with `left` property is very ugly.

How to enable CSS transitions?

**Comment by devmark** [comment]
please make a demo
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by emitremmus** [comment]
Where it is using "left" for animation?
http://devmark.github.io/angular-slick-carousel/#/

It is using tranlate3d for animation.

**Comment by artuska** [comment]
Somehow it was `left` — dunno, maybe it was some older version or something. Now I also cannot reproduce `left` positioning. I think this issue is not relevant anymore.
