### ISSUE TITLE
slickness.slick is not a function

### ISSUE THREAD

**Issue by anilselvaa** [devmark/angular-slick-carousel#66]
ionic.bundle.js:25644 TypeError: slickness.slick is not a function
    at angular-slick.js:167
    at ionic.bundle.js:31023
    at completeOutstandingRequest (ionic.bundle.js:18708)
    at ionic.bundle.js:18980

**Comment by devmark** [comment]
inject slick plugin before loading angular-slick

**Comment by generalgmt** [comment]
@devmark, 
Here is my imported files still having the same issue
<img width="435" alt="screen shot 2016-12-26 at 2 44 28 pm" src="https://cloud.githubusercontent.com/assets/7859083/21482874/03c493ee-cb7a-11e6-8f16-a7b83abdcc82.png">
<img width="421" alt="screen shot 2016-12-26 at 2 47 56 pm" src="https://cloud.githubusercontent.com/assets/7859083/21482897/5bc1af1e-cb7a-11e6-95a6-707de9364d21.png">

**Comment by generalgmt** [comment]
@devmark 
Here are my imported files:
<img width="435" alt="screen shot 2016-12-26 at 2 44 28 pm" src="https://cloud.githubusercontent.com/assets/7859083/21483087/45777d26-cb7d-11e6-91be-416605eb4fb7.png">

However, I'm still having the same error
<img width="421" alt="screen shot 2016-12-26 at 2 47 56 pm" src="https://cloud.githubusercontent.com/assets/7859083/21483089/4b58e2a2-cb7d-11e6-95f5-994ebe7ef5fb.png">
How can I go about fixing this?

**Comment by heshamelmasry77** [comment]
same problem
