### ISSUE TITLE
should re-init if config change failing

### ISSUE THREAD

**Issue by monotkate** [devmark/angular-slick-carousel#68]
When I run the unit tests for my program, this test is failing with a ```$digest already in progress``` error for line 83, or the second ```scope.$digest()``` in the test.  If I comment out that test, I can make it work with my program just fine.

Do you have any idea why this test is failing, or can I stop the tests from running?

**Comment by devmark** [comment]
Sorry for delay. 

fixed. will publish on 3.1.5
