### ISSUE TITLE
Hidden images still take space on update

### ISSUE THREAD

**Issue by Ya-Wang** [devmark/angular-slick-carousel#70]
First instance loads fine and @ update it works but it doesn't display:none the other images that aren't appose to show they still take up space. The fade in and out still works on auto timer. 

(zoomed out therefore placing is off but idea is there, black boxes are images)
![untitled](https://cloud.githubusercontent.com/assets/3073708/15326628/b43eef8e-1c1c-11e6-83d9-4e2c2c904999.png)

` $scope.displayDetails = function (product, scroll) {
        $scope.slickLoaded = false;
        if ($scope.showDetails) {
            $anchorScroll();
        }
        $scope.showDetails = true;
        $scope.currentProduct = product;
        $scope.lastScroll = scroll;
        $scope.slickLoaded = true;
    }`

` <slick ng-if="slickLoaded" autoplay="true" dots="true" infinite="true" autoplayspeed="500" fade="true">
                                        <div ng-repeat="image in currentProduct.Images track by $index" style="text-align:center">
                                            <img src="http://cdnll.site.com/images/1000/{{image}}.jpg" width="400" height="390" />
                                            <span>{{image.Id}}</span>
                                        </div>
                                   </slick>`

Also it seems like if I switch to a currentProduct with only one Image there are still multiple dots with no pictures associated with them.

**Comment by devmark** [comment]
Hello. 
please make a demo
you can fork from this: http://plnkr.co/edit/9goFW6?p=preview

**Comment by Ya-Wang** [comment]
Needed timeout...
