### ISSUE TITLE
nextSlide parameter is always `undefined`

### ISSUE THREAD

**Issue by artuska** [devmark/angular-slick-carousel#82]
This is my Sick config:

```
var carouselConfig = {
    speed: 500,
    infinite: true,
    draggable: false,
    slidesToShow: 1,
    slidesToScroll: 1,
    initialSlide: 0,
    lazyLoad: 'ondemand',
    event: {
        afterChange: function (e, slick, currentSlide, nextSlide) {
            console.log(nextSlide);
        }
    }
};
```

`nextSlide` parameter always returns `undefined` no matter of the Slick configuration, no matter if lazy loading is enabled or disabled... its just always is `undefined`.

'Cos it is not a big deal — I can calculate next slide from the `currentSlide` parameter, but I'm just saying :)

**Comment by devmark** [comment]
take a look 3.1.6
