### ISSUE TITLE
tabindex is always set to -1

### ISSUE THREAD

**Issue by ollamh** [devmark/angular-slick-carousel#88]
Hi! I would like a user to have a possibility to use TAB when switching between slides.  By default the tabindex attribute set to -1 (turned off). And accessibility attribute (which should turn on tabindex) doesn't help. Is this a slick issue or I miss something in a config object?

**Comment by claycarpenter** [comment]
@ollamh This tabindex problem looks to be an [issue in the Slick library](https://github.com/kenwheeler/slick/issues/2338).
