### ISSUE TITLE
Carousel does not get initialised if settings have not been defined after version 3.1.6

### ISSUE THREAD

**Issue by Yurko-Fedoriv** [devmark/angular-slick-carousel#91]
[This line](https://github.com/devmark/angular-slick-carousel/blob/3.1.6/dist/angular-slick.js#L295) prevents carousel initialisation in case all options were passed by attributes and ```seetings``` attribute was not defined at all.

Not sure what is an expected behavior, but this is confusing, does not correspond with [an example](https://github.com/devmark/angular-slick-carousel/blob/master/README.md), and also it's potentially breaking during migration from 3.1.5 to 3.1.6, which in general should not happen for minor release.

**Comment by chiester** [comment]
I also encountered this and worked around it by adding a settings attribute.

**Comment by devmark** [comment]
fix 3.1.7
