### ISSUE TITLE
Events not fired if # of slides less than 'slidesToShow'

### ISSUE THREAD

**Issue by flaviocysne** [devmark/angular-slick-carousel#95]
When the number of elements/slides are less than or equal the value configured in slidesToShow settings's property, no arrows or dots are rendered and events are not fired.

Sample: http://plnkr.co/edit/QqcVX7?p=preview

**Comment by sunilsd** [comment]
Hi Mark,
   Any update to this issue?
Regards...

**Comment by flaviocysne** [comment]
I figure it out that the problem relies at [kenwheeler/slick](https://github.com/kenwheeler/slick) code.

I registered an issue for this: https://github.com/kenwheeler/slick/issues/2821
