### ISSUE TITLE
Angular 2 & TypeScript

### ISSUE THREAD

**Issue by jessepinuelas** [devmark/angular-slick-carousel#97]
Is there a version of angular-slick-carousel for Angular 2 & TypeScript

**Comment by AshishNR** [comment]
Hi jesse, 

did you find any solution ? i am trying to add it in Angular 2 & Typescript . i am new to it . 

any help would be appreciate.  

Thanks,
Ashish

**Comment by jessepinuelas** [comment]
@AshishNR I did hope the following steps help you out.

**Install the following via typings and npm:**
typings install dt~jquery --save --global
typings install dt~slick-carousel --save --global
npm install slick-carousel --save

**Import slick into your component:**
`
  import * as $ from 'jquery';
  import 'slick-carousel/slick/slick';
`

**After your constructor add the following:**
`ngOnInit() {
        $('.carousel-class').slick({
            autoplay: false,
            dots: true,
            fade: true,
            arrows: false
        });
    }
`

**Comment by AshishNR** [comment]
Thanks.  Still have one issue . 

**import 'slick-carousel/slick/slick';**   =>  statement is throwing error .
Failed to load resource: the server responded with a status of 404 (Not Found). 

i have all required slick js library files in "bower_compnents\slick-carousel\slick" folder.

**Comment by AshishNR** [comment]
Thanks . found solution . 
https://github.com/systemjs/systemjs/issues/988

using styleUrls property  to load my jquery library . and it's able to convert my divs in to carousel control. 

Thanks again .

**Comment by AshishNR** [comment]
If typings commands are not working then we  need to install typings CLI Utility by below command. 
npm install typings --global

Got help From link :  https://github.com/typings/typings

**Comment by Silvercast** [comment]
I have hard time making Slick work with binding because Slick either accepts all data items at created time, or adds items dynamically via `slick.add(...)` API call. 
#compile is gone on Angular 2 so I'm basically stuck.

**Comment by VishalGulati** [comment]
Any progress on this. I am also stuck in implementing slick carousel/Coverflow functionality in angular2. Anyone having done that? Please share how to proceed on this. TIA

**Comment by shajeeck** [comment]
@AshishNR , @jessepinuelas  I am in a real need to implement slick in angular2
i am using angular2 cli to create a new project and i followed exactly what @jessepinuelas solution

but i am getting an  error "Cannot find module 'jquery'"
any solution??

**Comment by JayKan** [comment]
@shajeeck,

Import the followings at your `slick-sider` component, 
 - import * as jQuery from 'jquery';
 - import 'slick-caousel';

Make sure you have both @types/jquery, @types/slick-carousel typings installed and included in your tsconfig.json file.

Hopefully this can be helpful!

**Comment by thegrid22593** [comment]
@shajeeck
You need to install jquery and its typings.

` npm i jquery --save `
`npm i @types jquery --save-dev `

**In your component**
`import * $ from 'jquery'`

**Comment by zNiik** [comment]
When I'm importing slick-carousel using `import 'slick-carousel';` I'm getting Cannot set property 'slick' of undefined. Anybody knows how to fix this?

**Comment by samvloeberghs** [comment]
@jessepinuelas @thegrid22593 @JayKan consider cleaning up in ngOnDestroy():

ngOnDestroy(){
    ...
    $('.your-slider').slick('unslick');
}

**Comment by kblestarge** [comment]
Is it possible to use the slick-carousel without using jQuery as a dependency?

**Comment by csmonteloyola** [comment]
Hi! Have you tried using this with Angular 4?

**Comment by whcmark** [comment]
https://github.com/devmark/ngx-slick
